### ISSUE TITLE
[Bug] Error occurred when setup checkstyle plugin in IDEA

### ISSUE THREAD

**Issue by zhangyuewen12** [alibaba/fluss#160]
### Search before asking

- [X] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Motivation

com.puppycrawl.tools.checkstyle.api.CheckstyleException: 无法初始化模块 TreeWalker - cannot initialize module JavadocMethod - Property 'allowUndeclaredRTE' does not exist, please check the documentation
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:484)
	at com.puppycrawl.tools.checkstyle.AbstractAutomaticBean.configure(AbstractAutomaticBean.java:210)
	at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:61)
	at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:26)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:116)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:60)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:51)
	at org.infernus.idea.checkstyle.checker.CheckerFactoryWorker.run(CheckerFactoryWorker.java:42)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module JavadocMethod - Property 'allowUndeclaredRTE' does not exist, please check the documentation
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:160)
	at com.puppycrawl.tools.checkstyle.AbstractAutomaticBean.configure(AbstractAutomaticBean.java:210)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:479)
	... 7 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Property 'allowUndeclaredRTE' does not exist, please check the documentation
	at com.puppycrawl.tools.checkstyle.AbstractAutomaticBean.tryCopyProperty(AbstractAutomaticBean.java:236)
	at com.puppycrawl.tools.checkstyle.AbstractAutomaticBean.configure(AbstractAutomaticBean.java:203)
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:155)
	... 9 more

### Willingness to contribute

- [ ] I'm willing to submit a PR!

**Comment by gyang94** [comment]
Same error occurred when setup 'checkstyle'. After this step:
`8. Configure the property checkstyle.suppressions.file with the value suppressions.xml and click "Next".`

I'm working on IntelliJ IDEA 2024.1.2 (Ultimate Edition)

<img width="1007" alt="image" src="https://github.com/user-attachments/assets/17b876c7-7218-4b6c-aa14-2f99f5cb21bf" />

**Comment by luoyuxia** [comment]
Should be fix now. Let's close it.
