### ISSUE TITLE
[Test] FlinkCatalogITCase.testCreateNoPkTable is unstable

### ISSUE THREAD

**Issue by wuchong** [alibaba/fluss#215]
### Search before asking

- [X] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Fluss version

main

### Minimal reproduce step

https://github.com/alibaba/fluss/actions/runs/12367878332/job/34516893644?pr=126

```
[INFO] Tests run: 48, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 185.847 s - in com.alibaba.fluss.connector.flink.source.FlinkTableSourceITCase
Error:  Tests run: 9, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 616.219 s <<< FAILURE! - in com.alibaba.fluss.connector.flink.catalog.FlinkCatalogITCase
Error:  com.alibaba.fluss.connector.flink.catalog.FlinkCatalogITCase.testCreateNoPkTable  Time elapsed: 600.099 s  <<< ERROR!
org.apache.flink.table.api.TableException: Could not execute CreateTable in path `testcatalog`.`fluss`.`append_only_table`
	at org.apache.flink.table.catalog.CatalogManager.execute(CatalogManager.java:1367)
	at org.apache.flink.table.catalog.CatalogManager.createTable(CatalogManager.java:997)
	at org.apache.flink.table.operations.ddl.CreateTableOperation.execute(CreateTableOperation.java:86)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:1102)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeSql(TableEnvironmentImpl.java:735)
	at com.alibaba.fluss.connector.flink.catalog.FlinkCatalogITCase.testCreateNoPkTable(FlinkCatalogITCase.java:172)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:185)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.executeNonConcurrentTasks(ForkJoinPoolHierarchicalTestExecutorService.java:155)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at com.alibaba.fluss.shaded.netty4.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at com.alibaba.fluss.shaded.netty4.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at com.alibaba.fluss.shaded.netty4.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)

[INFO] 
[INFO] Results:
[INFO] 
Error:  Errors: 
Error:    FlinkCatalogITCase.testCreateNoPkTable:172 ? Table Could not execute CreateTab...
[INFO] 
Error:  Tests run: 82, Failures: 0, Errors: 1, Skipped: 0
```

### What doesn't meet your expectations?

unstable test

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by redpheonixx** [comment]
Hi @wuchong , I am new to the project and would love to pick up this issue. Can you guide me what is required.

**Comment by polyzos** [comment]
**FlinkTableSourceITCase.testLookup2PkTableWithUnorderedKey(Caching, boolean)[2]** is also unstable
https://github.com/alibaba/fluss/actions/runs/13452476111/job/37590731101?pr=457
```
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 32.217 s - in com.alibaba.fluss.connector.flink.metrics.FlinkMetricsITCase
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 84.044 s - in com.alibaba.fluss.connector.flink.source.FlinkTableSourceBatchITCase
[INFO] Tests run: 23, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 194.071 s - in com.alibaba.fluss.connector.flink.sink.FlinkTableSinkITCase
Error:  Tests run: 67, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 231.175 s <<< FAILURE! - in com.alibaba.fluss.connector.flink.source.FlinkTableSourceITCase
Error:  com.alibaba.fluss.connector.flink.source.FlinkTableSourceITCase.testLookup2PkTableWithUnorderedKey(Caching, boolean)[2]  Time elapsed: 8.621 s  <<< ERROR!
java.lang.RuntimeException: Failed to fetch next result
	at org.apache.flink.streaming.api.operators.collect.CollectResultIterator.nextResultFromFetcher(CollectResultIterator.java:129)
	at org.apache.flink.streaming.api.operators.collect.CollectResultIterator.next(CollectResultIterator.java:108)
	at org.apache.flink.table.planner.connectors.CollectDynamicSink$CloseableRowIteratorWrapper.next(CollectDynamicSink.java:254)
	at com.alibaba.fluss.connector.flink.source.testutils.FlinkTestBase.assertResultsIgnoreOrder(FlinkTestBase.java:176)
	at com.alibaba.fluss.connector.flink.source.FlinkTableSourceITCase.testLookup2PkTableWithUnorderedKey(FlinkTableSourceITCase.java:771)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
```
