### ISSUE TITLE
[Bug] Initialization of PeriodicSnapshotManager will throw ArithmeticException if `kv.snapshot.interval` is set to 0

### ISSUE THREAD

**Issue by cshuo** [alibaba/fluss#45]
### Search before asking

- [X] I searched in the [issues](https://github.com/alibaba/fluss/issues) and found nothing similar.

### Fluss version

0.6-SNAPSHOT

### Minimal reproduce step

following quick start: https://alibaba.github.io/fluss-docs/docs/quickstart/flink/

### What doesn't meet your expectations?

There should be no exceptions, as non-positive `periodicSnapshotDelay` is also valid parameter, in which scenario no periodic snapshot is scheduled.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by polyzos** [comment]
@cshuo can you share more context? what is the exception you are getting?

**Comment by cshuo** [comment]
```
2024-11-29 07:04:42,247 ERROR com.alibaba.fluss.server.replica.Replica                     [] - init kv periodic snapshot failed.
java.lang.ArithmeticException: / by zero
	at com.alibaba.fluss.server.kv.snapshot.PeriodicSnapshotManager.<init>(PeriodicSnapshotManager.java:122) ~[fluss-server-0.5.0.jar:0.5.0]
	at com.alibaba.fluss.server.kv.snapshot.PeriodicSnapshotManager.create(PeriodicSnapshotManager.java:138) ~[fluss-server-0.5.0.jar:0.5.0]
	at com.alibaba.fluss.server.replica.Replica.startPeriodicKvSnapshot(Replica.java:752) ~[fluss-server-0.5.0.jar:0.5.0]
	at com.alibaba.fluss.server.replica.Replica.createKv(Replica.java:519) ~[fluss-server-0.5.0.jar:0.5.0]
	at com.alibaba.fluss.server.replica.Replica.onBecomeNewLeader(Replica.java:495) ~[fluss-server-0.5.0.jar:0.5.0]
	at com.alibaba.fluss.server.replica.Replica.lambda$makeLeader$3(Replica.java:359) ~[fluss-server-0.5.0.jar:0.5.0]
	at com.alibaba.fluss.utils.concurrent.LockUtils.inLock(LockUtils.java:41) ~[fluss-server-0.5.0.jar:0.5.0]
	at com.alibaba.fluss.utils.concurrent.LockUtils.inWriteLock(LockUtils.java:64) ~[fluss-server-0.5.0.jar:0.5.0]
	at com.alibaba.fluss.server.replica.Replica.makeLeader(Replica.java:344) ~[fluss-server-0.5.0.jar:0.5.0]
	at com.alibaba.fluss.server.replica.ReplicaManager.makeLeaders(ReplicaManager.java:652) ~[fluss-server-0.5.0.jar:0.5.0]
	at com.alibaba.fluss.server.replica.ReplicaManager.lambda$becomeLeaderOrFollower$3(ReplicaManager.java:321) ~[fluss-server-0.5.0.jar:0.5.0]
	at com.alibaba.fluss.utils.concurrent.LockUtils.inLock(LockUtils.java:31) [fluss-server-0.5.0.jar:0.5.0]
	at com.alibaba.fluss.server.replica.ReplicaManager.becomeLeaderOrFollower(ReplicaManager.java:297) [fluss-server-0.5.0.jar:0.5.0]
	at com.alibaba.fluss.server.tablet.TabletService.notifyLeaderAndIsr(TabletService.java:162) [fluss-server-0.5.0.jar:0.5.0]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at com.alibaba.fluss.rpc.netty.server.RequestProcessor.processRequest(RequestProcessor.java:108) [fluss-server-0.5.0.jar:0.5.0]
	at com.alibaba.fluss.rpc.netty.server.RequestProcessor.run(RequestProcessor.java:84) [fluss-server-0.5.0.jar:0.5.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by polyzos** [comment]
You copy/paste the `docker-compose.yaml` file from the quickstart and when running `docker compose up` it throws this exception? or is it on a different step?

**Comment by cshuo** [comment]
> You copy/paste the `docker-compose.yaml` file from the quickstart and when running `docker compose up` it throws this exception? or is it on a different step?

Yeah, you can reproduce it just following the steps in the quick start. But It do not affect the main flow, I just find it as an error log. Anyway, I think it's better to solve it.

**Comment by polyzos** [comment]
I'm unable to replicate it but will keep an eye on this. Thanks for reporting it 👍

**Comment by luoyuxia** [comment]
@cshuo Thanks for reporting.. It does a issue. In [here](https://github.com/alibaba/fluss/blob/main/fluss-server/src/main/java/com/alibaba/fluss/server/kv/snapshot/PeriodicSnapshotManager.java#L122), we don't handle when periodicSnapshotDelay is 0, so `java.lang.ArithmeticException: / by zero` is throw. It should be a quick fix.

**Comment by cshuo** [comment]
@luoyuxia I'm willing to make a quick hotfix. 🫡
